### PR TITLE
ADDED beach sprites

### PR DESCRIPTION
**Pull request by ChifuyuOnWish**

### CODE REVIEW

**Review by Nolfews — COMMENTED** [review]
perfect pixel for tuiles

**Review by Nolfews — APPROVED** [review]

**Review by landryarki — APPROVED** [review]

**Review by eliotttesnier — COMMENTED** [review]
WOW

**Review by Thomaltarix — APPROVED** [review]
:+1:

**Review by NathanBezard — APPROVED** [review]

**Review by eliotttesnier — APPROVED** [review]
wow

**Pull request merged**
